#!/bin/sh

userresources="$XDG_CONFIG_HOME"/X11/xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start gtk and systemd user
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Try to prevent sleep on idle
xset s off -dpms

xrandr --output DP-2 --auto --output DP-5 --auto --left-of DP-2
setxkbmap -option caps:escape
nitrogen --restore &
picom --config $XDG_CONFIG_HOME/picom/picom.conf &
redshift &
xsetroot -cursor_name left_ptr &
exec xmonad
