#!/bin/sh

userresources="$XDG_CONFIG_HOME"/X11/xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set the resolution for the VM
# xrandr --output Virtual-1 --mode 1920x1200
# Remap caps lock to escape
xrandr --output DP-2 --auto --output DP-5 --auto --left-of DP-2
setxkbmap -option caps:escape
nitrogen --restore &
picom --config $XDG_CONFIG_HOME/picom/picom.conf &
xsetroot -cursor_name left_ptr &
dropbox &
exec xmonad
