#!/bin/bash
bluetoothctl power on
connected=`bluetoothctl info | grep "E4:90:FD:90:2B:52" -A 8 | grep "Connected" | awk '{ print $2 }'`

if [ -z $1 ]
then
	if [[ $connected == 'yes' ]]
	then
		bluetoothctl disconnect E4:90:FD:90:2B:52
	else
		bluetoothctl connect E4:90:FD:90:2B:52
	fi
else
	case $1 in
		connect)
			bluetoothctl connect E4:90:FD:90:2B:52
			;;
        c)
            airpods connect
            ;;
		disconnect)
			bluetoothctl disconnect E4:90:FD:90:2B:52
			;;
        d)
            airpods disconnect
            ;;
	esac
fi

