#!/bin/bash
bluetoothctl power on
connected=`bluetoothctl info | grep "E4:90:FD:90:2B:52" -A 8 | grep "Connected" | awk '{ print $2 }'`

if [ $connected == 'yes' ]
then
    bluetoothctl disconnect E4:90:FD:90:2B:52
else
    bluetoothctl connect E4:90:FD:90:2B:52
fi

