#!/bin/bash

function get_brightness {
  xbacklight -get | cut -d '.' -f 1
}

function lap_notification {
  icon="/usr/share/icons/Qogir-dark/16/panel/gpm-brightness-lcd.svg"
  brightness=$(get_brightness)
  # Make the bar with the special character ─ (it's not dash -)
  # https://en.wikipedia.org/wiki/Box-drawing_character
  bar=$(seq -s "─" 0 $((brightness / 3)) | sed 's/[0-9]//g')
  # Send the notification
  dunstify -i "$icon" -r 5555 -u normal " $bar"
}



function mon_notification {
  icon="/usr/share/icons/Qogir-dark/16/panel/gpm-brightness-lcd.svg"
  brightness=$(sudo ddcutil getvcp 10 | awk '{ print $9 }' | sed 's/,//g')
  # Make the bar with the special character ─ (it's not dash -)
  # https://en.wikipedia.org/wiki/Box-drawing_character
  bar=$(seq -s "─" 0 $((brightness / 3)) | sed 's/[0-9]//g')
  # Send the notification
  dunstify -i "$icon" -r 5555 -u normal " $bar"
}

if xrandr | grep "DP3 connected"
then
  case $1 in
    up)
      sudo ddcutil setvcp 10 + 2
      mon_notification
      ;;
    down)
      sudo ddcutil setvcp 10 - 2
      mon_notification
      ;;
    set)
      sudo ddcutil setvcp 10 $2
      mon_notification
      ;;
  esac
else
  case $1 in
    up)
      xbacklight -inc 2
      lap_notification
      ;;
    down)
      xbacklight -dec 2
      lap_notification
      ;;
    set)
      xbacklight -set $2
      lap_notification
      ;;
  esac
fi

