#!/bin/bash

function get_brightness {
  xbacklight -get | cut -d '.' -f 1
}

function send_notification {
  icon="/usr/share/icons/Qogir-dark/16/panel/gpm-brightness-lcd.svg"
  brightness=$(get_brightness)
  echo $brightness
  # Make the bar with the special character ─ (it's not dash -)
  # https://en.wikipedia.org/wiki/Box-drawing_character
  bar=$(seq -s "─" 0 $((brightness / 3)) | sed 's/[0-9]//g')
  # Send the notification
  dunstify -i "$icon" -r 5555 -u normal " $bar"
}

case $1 in
  up)
    xbacklight -inc 2
    send_notification
    ;;
  down)
    xbacklight -dec 2
    send_notification
    ;;
esac
