#!/bin/bash

case $1 in
    kite)
        sudo chmod a+x ~/.config/nvim/pack/kite/start/vim-plugin/lib/linux/kite-http
        ;;

    monitor)
        xrandr --output DP-2 --off --output DP-5 --off
        xrandr --output DP-2 --primary --mode 2560x1440 --output DP-5 --mode 1920x1080 --left-of DP-2
        ;;
esac
